module.exports = {
  koa: {
    dependencies: [
      'koa',
      'koa-bodyparser',
      'koa-compress',
      'koa-helmet',
      'koa-logger',
      'koa-response2',
      'koa-router',
      '@koa/cors',
      '@koa/multer',
      'multer',
      'winston',
      'morgan',
      'redis',
      'dotenv',
      'ts-node',
      'clinic'
    ],
    devDependencies: [
      '@types/koa',
      '@types/koa-bodyparser',
      '@types/koa-compress',
      '@types/koa-helmet',
      '@types/koa-logger',
      '@types/koa-router',
      '@types/koa__cors',
      '@types/koa__multer',
      '@types/multer',
      '@types/koa-multer',
      '@types/morgan',
      '@types/mocha',
      '@types/chai',
      '@types/redis',
      'typescript',
      'ts-node-dev',
      "@typescript-eslint/eslint-plugin",
      "@typescript-eslint/parser",
      '@tsconfig/node12',
      'husky',
      'eslint',
      'prettier',
      'pretty-quick',
    ],
  },
};
