module.exports = function(){
    return `{"$schema": "https://json.schemastore.org/tsconfig",
"display": "Node 14",

"extends": "@tsconfig/node14/tsconfig.json",  
"compilerOptions": {
  "baseUrl": "./",
  "lib": ["es2019", "es2020.promise", "es2020.bigint", "es2020.string"],
  "module": "ES2020",
  "moduleResolution": "node",
  "target": "es2020",
  "types":["node", "webgl2"],
  "outDir": "dist",
  "strict": true,
  "noUnusedLocals": true,
  "noUnusedParameters": true,
  "strictNullChecks": true,
  "noImplicitReturns": true,
  "noUncheckedIndexedAccess": true,
  "alwaysStrict": true,
  "strictFunctionTypes": true,
  "strictBindCallApply": true,
  "strictPropertyInitialization": true,
  "allowUnreachableCode": false,
  "noFallthroughCasesInSwitch": true,
  "allowSyntheticDefaultImports": true,
  "resolveJsonModule": true,
  "esModuleInterop": true,
  "skipLibCheck": true,
  "forceConsistentCasingInFileNames": true,
  "noImplicitAny": true,
  "noImplicitThis": true,
  "experimentalDecorators": true,
  "emitDecoratorMetadata": true,
  "sourceMap": true,
  "declaration": true,
  "declarationMap": true
},  
"include": ["index.ts","server/**/*"],
"exclude": ["node_modules"]
}`
}